config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#show"

  get '/games', to: "games#index"
  get '/platforms', to: "platforms#index"
  get '/companies', to: "companies#index"
  get '/load_data', to: "data#index"

  namespace :maps do
    get '/companies', to: "companies#index"
  end

  namespace :platforms do
    get '/sales', to: "sales#index"
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get '/platforms', to: "platforms#index"
      get '/companies', to: "companies#index"
      get '/games', to: "games#index"
    end
  end

  get '/auth/github', as: :github_login
  get '/auth/github/callback', to: 'sessions#create'
  get "/logout", to: "sessions#destroy", as: "github_logout"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord

  def self.known_dates_founded
    self.where.not(date_founded: nil)
  end

  def self.valid_companies
    known_dates_founded.where.not(location_country: nil)
  end

  def self.top_five_newest_companies
    valid_companies.order(:date_founded).last(5)
  end
end

app/models/data_saver.rb
class DataSaver
  attr_reader :giantbomb_service

  def initialize
    @giantbomb_service ||= GiantBombService.new
  end

  def save_companies
    giantbomb_service.load_companies.each do |company|
      Company.find_or_create_by(company)
    end
  end

  def save_platforms
    giantbomb_service.load_platforms.each do |platform|
      base         = platform["install_base"].to_i
      price        = platform["original_price"].to_f
      name         = platform["name"]
      release_date = platform["release_date"]


      Platform.find_or_create_by(
        name: name,
        install_base: base,
        original_price: price,
        release_date: release_date
      )
    end
  end

  def save_games
    giantbomb_service.load_games.each do |game_data|
      Game.find_or_create_by(game_data)
    end
  end
end

app/models/game.rb
class Game < ApplicationRecord

  def self.valid_games
    self.where.not(name: nil).where.not(original_release_date: nil)
  end

  def self.top_five_newest_games
    valid_games.order(:original_release_date).last(5)
  end
end

app/models/permission.rb
class Permission
  attr_reader :user, :controller, :action

  def initialize(user)
    @user = user || User.new
  end

  def allow?(controller, action)
    @controller = controller
    @action     = action

    if user.logged_in?
      registered_user_permissions
    else
      guest_user_permissions
    end
  end

  private

    def registered_user_permissions
      return true if controller == "home"
      return true if controller == "games"
      return true if controller == "platforms"
      return true if controller == "companies"
      return true if controller == "games"
      return true if controller == "data"
      return true if controller == "sessions"
      return true if controller == "platforms/sales"
      return true if controller == "maps/companies"
      return true if controller == "api/v1/platforms"
      return true if controller == "api/v1/games"
      return true if controller == "api/v1/companies"
    end

    def guest_user_permissions
      return true if controller == "home"
      return true if controller == "sessions"
      return true if controller == "api/v1/platforms"
      return true if controller == "api/v1/games"
      return true if controller == "api/v1/companies"
    end
end

app/models/platform.rb
class Platform < ApplicationRecord
  before_save :calculate_total_revenue

  def calculate_total_revenue
    self.total_revenue = self.install_base * self.original_price
  end

  def self.valid_platforms
    self.where.not(release_date: nil)
  end

  def self.top_five_newest_platforms
    valid_platforms.order(:release_date).last(5)
  end
end

app/models/user.rb
class User < ApplicationRecord

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.username           = auth_info.extra.raw_info.login
      new_user.auth_token         = auth_info.credentials.token
    end
  end

  def logged_in?
    self.username != nil
  end
end

app/controllers/api/v1/companies_controller.rb
class Api::V1::CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end
end

app/controllers/api/v1/games_controller.rb
class Api::V1::GamesController < ApplicationController
  def index
    @games = Game.all
  end
end

app/controllers/api/v1/platforms_controller.rb
class Api::V1::PlatformsController < ApplicationController
  def index
    @platforms = Platform.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

    helper_method :current_user

    add_flash_types :success,
                    :info,
                    :warning,
                    :danger

    before_action :authorize!

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def current_permission
      @current_permission ||= Permission.new(current_user)
    end

    def authorize!
      unless authorized?
        redirect_to '/', danger: "Login to browse content"
      end
    end

    def authorized?
      current_permission.allow?(params[:controller], params[:action])
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index

  end
end

app/controllers/data_controller.rb
class DataController < ApplicationController

  def index
    LoadCompaniesWorker.perform_async
    LoadPlatformsWorker.perform_async
    LoadGamesWorker.perform_async

    flash[:success] = "Now Searching for New Data"
    redirect_to root_path
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/maps/companies_controller.rb
class Maps::CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end
end

app/controllers/platforms/sales_controller.rb
class Platforms::SalesController < ApplicationController
  def index
    @platforms = Platform.all
    # LoadCompaniesWorker.perform_async
  end
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  def index
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
      redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/index.html.erb
<div class="container">
  <p style="text-align:center">
    Ever Wonder What Gaming Companies Are Out There? Now You Know.
  </p>

  <div id="all-companies">

  </div>

</div>

app/views/games/index.html.erb
<div class="container">
  <div class="container">
    <p style="text-align:center">
      Ever Wonder What Games Are Out There? Here's a few!
    </p>

  <div id="all-games">

  </div>
</div>

app/views/home/show.html.erb
<div class="banner">
  <h1 class="banner-text">
    ApexGamer
    <p style="font-size: 25px">
      Learn to be the best.
    </p>
  </p>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
<div class="primary callout" data-closable>
  <h5 class="popup"><%= message %></h5>
  <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li><%= link_to "ApexGamer", root_path %></li>
      <li>
        <a href="#">Categories</a>
        <ul class="menu vertical">
          <li><%= link_to "Games", games_path %></li>
          <li><%= link_to "Companies", companies_path %></li>
          <li><%= link_to "Platforms", platforms_path %></li>
        </ul>
      </li>
      <li>
        <a href="#">Charts</a>
        <ul class="menu vertical">
          <li><%= link_to "Country Map", maps_companies_path %></li>
        </ul>
      </li>
      <li><%= link_to "Click to Update Data", load_data_path %></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="dropdown menu" data-dropdown-menu>
      <li>
        <% if current_user %>
        <a href="#"><%= current_user.username %></a>
        <ul class="menu vertical">
          <li><%= link_to "Logout", github_logout_path %></li>
        </ul>
        <% else %>
          <%= link_to "Login with Github", github_login_path %>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "chartkick" %>
    <%= javascript_include_tag "https://www.google.com/jsapi" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/navbar' %>

    <div class="flash-messages">
      <%= render 'layouts/flash' %>
    </div>

    <%= yield %>

  </body>
</html>

app/views/maps/companies/index.html.erb
<p style="text-align:center">
  Ever Wondered What Countries Have the Most Gaming Companies?
</p>
<div id="map">
  <% cache("companies-map") do %>
    <%= geo_chart @companies.group(:location_country).count %>
  <% end %>
</div>

app/views/maps/companies/show.html.erb
<p style="text-align:center">
  Ever Wondered What Countries Have the Most Gaming Companies?
</p>
<div id="map">
  <%= geo_chart @companies.group(:location_country).count %>
</div>

app/views/platforms/index.html.erb
<div class="container">
  <p style="text-align:center">
    Gaming Platforms For Decades. See How Many You Know.
  </p>

  <div id="all-platforms">

  </div>
</div>

app/views/platforms/sales/index.html.erb
All Platforms

<div class="all-platforms">

</div>

<%= javascript_include_tag "platforms" %>